name: Build
on:
  push

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  trunk_check:
    name: Trunk Check Runner
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN}}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          override: true

      - name: Setup Trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          # Optional version of trunk to install(eg. 'v0.16.0', 'latest')
          version: 'latest'

      - name: Trunk Build
        shell: bash
        run: trunk build --release

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup minify-js
        run: |
          npm install -g minify
          find . -name "*.js" -exec bash -c 'mv {} {}_; cat {}_ | minify --js > {}; rm {}_' \;
          find . -name "*.css" -exec bash -c 'mv {} {}_; cat {}_ | minify --css > {}; rm {}_' \;


      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
